### PR TITLE
add --error-on-freq-calc to improve scoring efficiency

### LINKED ISSUE #112: Improve efficiency of scoring
### Description of feature

I noticed that when using genotype data that contains a large number of samples/variants (Eg. TOPMed imputed genotypes), the plink2 scoring step is quite prolonged. I think that performance could be improved by adding the `--error-on-freq-calc` argument to `plink2` in `plink2_score.nf`:

https://github.com/PGScatalog/pgsc_calc/blob/c42dd1dee7208ab2f58a726e83234f348f5ea37d/modules/local/plink2_score.nf#L40-L47

Plink spends a large amount of time calculating allele frequencies, but when the number of variants in the genotype file is much greater than the number of variants in the scoring file, a large amount of time is wasted on this operation that doesn't seem directly relevant to scoring. Passing the `--error-on-freq-calc` argument asserts that frequencies aren't used (which given the current use of `no-mean-imputation` is valid), and should considerably improve performance: <http://cog-genomics.org/plink/2.0/input#read_freq>

### PR DESCRIPTION
**Pull request by nebfield**
closes #112

### CODE REVIEW

**Review by smlmbrt — APPROVED** [review]
Looks correct to me! We should add a check in `2.1.0` to make sure that no variants are dropped on user-specified data though, not just in the test.

**Comment by raimondsre** [comment]
Hi, could it be so that addition of --error-on-freq-calc in 2.0 results in missing genotypes being completely ignored? Rather than imputed as allele frequencies at some point? I run simulations with a single sample missing data and it appears to skip imputation now
[PGS_adding_new_sample_evaluation_gh.pdf](https://github.com/PGScatalog/pgsc_calc/files/12731916/PGS_adding_new_sample_evaluation_gh.pdf)

**Comment by raimondsre** [comment]
Hi, could it be so that addition of --error-on-freq-calc in 2.0 results in missing genotypes being completely ignored? Rather than imputed as allele frequencies at some point? I run simulations with a single sample missing data and it appears to skip imputation now
PGS_adding_new_sample_evaluation_gh

**Comment by smlmbrt** [comment]
Fixed in [v2.0.0-alpha.3](https://github.com/PGScatalog/pgsc_calc/releases/tag/v2.0.0-alpha.3), thanks for spotting @raimondsre!

**Pull request merged**
